namespace OpenH264.Intermediaries;

public enum DecoderOption
{
    DECODER_OPTION_END_OF_STREAM = 1,
    DECODER_OPTION_VCL_NAL,
    DECODER_OPTION_TEMPORAL_ID,
    DECODER_OPTION_FRAME_NUM,
    DECODER_OPTION_IDR_PIC_ID,
    DECODER_OPTION_LTR_MARKING_FLAG,
    DECODER_OPTION_LTR_MARKED_FRAME_NUM,
    DECODER_OPTION_ERROR_CON_IDC,
    DECODER_OPTION_TRACE_LEVEL,
    DECODER_OPTION_TRACE_CALLBACK,
    DECODER_OPTION_TRACE_CALLBACK_CONTEXT,
    DECODER_OPTION_GET_STATISTICS,
    DECODER_OPTION_GET_SAR_INFO,
    DECODER_OPTION_PROFILE,
    DECODER_OPTION_LEVEL,
    DECODER_OPTION_STATISTICS_LOG_INTERVAL,
    DECODER_OPTION_IS_REF_PIC,
    DECODER_OPTION_NUM_OF_FRAMES_REMAINING_IN_BUFFER,
    DECODER_OPTION_NUM_OF_THREADS,
}